name: Buildozer Android APK

on: [push]

jobs:
  build:
    # 使用一个公认稳定的操作系统版本
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 直接调用专业的 Buildozer 打包工具
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.2.1
        id: buildozer
        with:
          # 要执行的命令
          command: buildozer -v android debug
          # buildozer的工作目录
          build_dir: .buildozer

      # 上传由打包工具生成的 APK 文件
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          # ${{ steps.buildozer.outputs.filename }} 是打包工具的输出变量
          path: ${{ steps.buildozer.outputs.filename }}
