name: Buildozer Android APK

on: [push]

jobs:
  build:
    # 强制使用一个稳定、成熟的操作系统版本，杜绝环境变化带来的问题
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 增加 setuptools 和 wheel 增强稳定性
          pip install buildozer cython setuptools wheel
          sudo apt-get update
          # 使用与 ubuntu-22.04 匹配的依赖库，特别是 libtinfo5
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/
